name: avataa-platform

# x-logging: &logging
#   logging:
#     driver: loki
#     options:
#       loki-url: http://loki:3100/loki/api/v1/push
#       loki-external-labels: job=dockerlogs,owner=avataa,environment=${PLATFORM_PROJECT_ENVIRONMENT:?}

x-logging: &logging
  logging:
    options:
      max-size: 100m

x-networks: &networks
  networks:
    - avataa-platform

x-restart: &restart
  restart: always

networks:
  avataa-platform:
    external: true


services:

  inventory-comments:
    <<: [*logging, *networks, *restart]
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/ms/inventory-comments:${INVENTORY_COMMENTS_VERSION:?}
    container_name: inventory-comments
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/8000 || exit 1'"]
      interval: 3s
      timeout: 1s
      retries: 10
    hostname: inventory-comments
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4000M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 100M

  inventory-comments-healthcheck:
    <<: *networks
    image: ${REGISTRY_URL:?}/${PLATFORM_PROJECT_NAME:?}/curl:${HEALTHCHECK_VERSION:?}
    container_name: inventory-comments-healthcheck
    depends_on:
      inventory-comments:
        condition: service_healthy
